---
name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Check docker install
        run: |
          set -e
          docker info
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r test-requirements.txt
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Test with molecule
        run: |
          export ANSIBLE_MODULE_UTILS=$PWD/module_utils
          molecule create
          molecule converge -- --tags test_replica_factor
          molecule prepare --force
          molecule converge -- --tags test_partitions
          molecule prepare --force
          molecule converge -- --tags test_partitions_and_replica_factor
          molecule converge -- --tags test_partitions_and_replica_factor_default
          molecule prepare --force
          molecule converge -- --tags test_options
          molecule prepare --force
          molecule converge -- --tags test_consumer_lag
          molecule converge -- --tags test_delete
          molecule converge -- --tags test_acl_create
          molecule converge -- --tags test_acl_delete
          molecule prepare --force
          molecule converge -- --tags test_kafka_info_topics
          molecule converge -- --tags test_kafka_info_brokers
          molecule converge -- --tags test_kafka_info_consumer_groups
          molecule converge -- --tags test_check_mode_topic_delete
          molecule converge -- --tags test_check_mode_topic_update
          molecule converge -- --tags test_check_mode_topic_create
          molecule converge -- --tags test_check_mode_acl_delete
          molecule converge -- --tags test_check_mode_acl_create
